### ISSUE TITLE
DOes not work

### ISSUE THREAD

**Issue by Jacob4354652** [rxzyx/GimKit-Hacks#18]
This does not work. I put it into google chrome bar when having gimkit open and sends me to something else.

**Comment by PierceMichael** [comment]
you have to put it in the console not the search bar

**Comment by Jacob4354652** [comment]
Sorry I meant to say I put it in the console and I put how much money I want and I don’t get it

**Comment by rxzyx** [comment]
You do it before you join.

**Comment by Jacob4354652** [comment]
![Screenshot 2022-12-03 181147](https://user-images.githubusercontent.com/119441697/205466009-dd5b0404-57ef-4786-a1bc-55ef7ef95c1f.jpg)
Look at this. This is how it doesn't work. I did this before putting the code in
