### ISSUE TITLE
show awnsers and auto bot don't work

### ISSUE THREAD

**Issue by gamepier** [rxzyx/GimKit-Hacks#4]
**Describe the bug**
for both of them when i put them in the console and press enter i get a ton of errors

**To Reproduce**
1. Go to 'a random gimkit'
2. Click on 'console'
3. Scroll down to 'the input bar and put in the code.'

**Expected behavior**
it should highlight the awnsers or automaticly put in the awnsers

**Screenshots**
i don; t have

**Desktop (please complete the following information):**
 - OS: Chrome OS
 - Browser chrome
 - Version idk

**Additional context**

**Comment by rxzyx** [comment]
Sorry for that, the problem will be fixed shortly.

**Comment by WallOfMessages** [comment]
bro you dont close issues if you dont fix them 💀
