### ISSUE TITLE
Error when trying to use cash generator

### ISSUE THREAD

**Issue by DailyPigeon** [rxzyx/GimKit-Hacks#7]
When I enter a value after running the code the following error is displayed 

Uncaught TypeError: Cannot set properties of null (setting 'startingCash')
    at <anonymous>:1:34635
    at <anonymous>:1:35959

I am a beginner programmer and not very familiar with Js, so I don't know what this could mean. If I am running the code incorrectly or there is something that I am missing please let me know.

**Screenshot**
![image](https://user-images.githubusercontent.com/85699259/197366192-ee7f577f-68cd-4e9f-8e75-ea258e9fb8d0.png)

![image](https://user-images.githubusercontent.com/85699259/197366263-76aa61ca-c8ef-439b-a2fc-235050f6747f.png)

**Desktop**
 - OS: Windows 11
 - Browser: Chrome

**Comment by rxzyx** [comment]
Has to be in game so you can use it in the next.
